### feature Engineering

In [ ]:
- so far we performed feature analysis
     - Data frame qucik checks
     - Cetegorical column analaysis
     - Bar chart, Pie chart
     - Numerical  columns analaysis
     - Histograme , box plots, Outliers
     - Bi-multi varite analaysis
     - correlation etc
- Now we need to learn ferature Engineering
     - we will create a new column foe better ML model
     - we will perform the **encoding** which is convert Categorival to Numerical data
     - we will do **Transformatiom**
     - we will perfrom **Scaling: Standardlization and Normalayzetion**
     - We will perform Scalling: Standardization and Normalization
     - We will perform the Missing values analysis
     - Simply feature engneering means our data will be modified4

**Emcoding**
- Encoding means convert categorical data to Numerical data
- ML/DL or any madel works based on maths
- Modul can not understand english
- so it is very imp to convert categorical lables to numerical values................
- .
- .
-

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
path="winequality_red.csv"
wine_df=pd.read_csv(path)
wine_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [3]:
path="visadataset.csv"
visa_df=pd.read_csv(path)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [4]:

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [5]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

- Certified should assigne as 0
- Denide should assigne as 1

In [6]:
d={'Certifide': 0,'Denide': 1}
d

{'Certifide': 0, 'Denide': 1}

In [7]:
visa_df['case_status']=visa_df['case_status'].map(d)
visa_df['case_status']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
25475   NaN
25476   NaN
25477   NaN
25478   NaN
25479   NaN
Name: case_status, Length: 25480, dtype: float64

In [8]:
visa_df['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [9]:
d={}
d['Asia']=0
d['Africa']=1
d['North America']=2
d['Europe']=3
d['South America']=4
d['Oceania']=5
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [10]:
label=visa_df['continent'].unique()

In [11]:
lables=sorted(visa_df['continent'].unique())
d={}
for i,j in enumerate(lables):
    d[j]=i
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [12]:
l=["Apple","Banana"]
for i in range(len(1)):

_IncompleteInputError: incomplete input (4249373776.py, line 3)

In [ ]:
lables=sorted(visa_df['continent'].unique())
d={j:i for i,j in enumerate(lables)}
visa_df['continent']=visa_df['continent'].map(d)

In [15]:
path="visadataset.csv"
visa_df=pd.read_csv(path)
cat=visa_df.select_dtypes(include='object').columns


# i need to repeate above 3 line for all cat column
# except case_id
for i in cat:
    lables=sorted(visa_df[i].unique())
    d={j:i for i,j in enumerate(lables)}
    visa_df[i]=visa_df[i].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [ ]:
#   1 reade the data
get the cat column
for loop on cat start with 1
# lables=sorted(visa_df['continent'].unique())
# d={j:i for i,j in enumerate(lables)}
# visa_df[i]=visa_df[i].map(d)

### LableEncoder
- lableEnocder is a method will convert lables to numeric values
- It is under package: **sklearn (sickit-learn)**
  - the class Name is : preprocessing
     - the method name : LabelEncoder

In [16]:
# from <package>.<class> import<Method>
from sklearn.preprocessing import LabelEncoder

- step-1: impoet the method
-  step-2: save the method
-  step-3: apply fit transform
- **fit transform**
  - fit means find the logic
    - in above example fit means cerate mapper or dict
  -

In [19]:
path="visadataset.csv"
visa_df=pd.read_csv(path)
cat=visa_df.select_dtypes(include='object').columns

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

visa_df['case_status']=le.fit_transform(visa_df['case_status'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [23]:
from sklearn.preprocessing import LabelEncoder

for i in cat:
    le=LabelEncoder()
    
    visa_df['continent']=le.fit_transform(visa_df['continent'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

### OneHotEncoder
- First how many lables are there in a column
- that  many nwe
- for ex case status has two
  - Certified
  - Denied
- So It will create Two new extra columns
  - csae_states_Cretified
  - case_states_Denide
- At a time one column value become 1 other column value become 0
- this means a *OneHotEncoder*

|case_status|Case_status_Certified|Case_status_Denied|
|-|-|-|
|Certified|1|0|
|Denied|0|1|

### pd.get_dummies

In [26]:
path="visadataset.csv"
visa_df=pd.read_csv(path)
cat=visa_df.select_dtypes(include='object').columns
pd.get_dummies(visa_df['case_status'],dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]

In [25]:
visa_df['case_status']

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object